(×@tT×@tT×4
eFÿeFÿeFÿeF×@tT×@eFÿeFÿep@eFÇ@eFÿŸ@eFÿâ¶@eFÿeFÿep¶¶Ÿ
g¨‡°ÿÍg¨‡°ÿÍg¨‡°ÿÍg¨‡°ÿÍg¨‡°ÿÍg¨‡¨‡¨‡¨‡¨‡°Fÿ¬F×@tT×°Fÿ¶ÿ¶×(T×¶×]¶ÿK	eFÿ»d]k˜Ÿê›¿@pFÇÿ^¶×(T×¶×]›¿@pFÿ¬K¶gkSrk˜.Ç@eFs:ëÿ	í˜.×xdIé»d]@eFÿeFÿeFd	¨R˜ÿ¶xep@tÿ¶¶×	×@tT×@eFs]„@eFjtT×4
eFÿeFÿeeFÿ¬»d	seFŸ¨‡FT×4Í×@tT×R°Í»d	¨‡ôkÿ¶Lktÿ¶»d]ep@eFÇ@eFÿŸ@eFÿâjLkeFx¨‡@tT×@eFÿeFÿeFd	¨RTÿ¶í¶Ÿk˜k‡Fÿ¬K¶VC¼°(	¨‡°ÿÍg¨‡Ø”ÍrF»d.×ØI¨‡¨‡¨‡»d	íT	íÿ¶ÿ¶×¨‡@tT×@eFÿeFÿeFs&@tT×R°Í»T×³¶í(	¨‡°ÿÍg¨‡Ø”ÍrTqFÿ¬rTeFÿep@eFÇ@eFÿe»d@pFÿ¬K¶gkSrk˜ÿÍó³kÿ¶Lktÿ¶F»d¿@pF»d]øepFÿ¬FÿŸ@tT×¨‡»d	íeFÿ¶ÿ¶×(T×¶×]¶ÿK	eFÿe¿@pFÿ¬K	íT	íÿ¶ÿ¶×¨‡@tT×@eFÿeFÿeFsg»d@Fÿâj¯@tT×@eFÿeFÿeFd	í»d	¨‡ôkÿ¶Lktÿ¶›¿@pFÿ¬Kp.Çk,TeFÿepFÿ¬FkeFeF»d	eFÿe¿@pp.Çk,TeFÿepFÿ¬FkeFeF»d	eFÿe¿@pp.Çk,TeFÿepFÿ¬FkeFeF»d	eFÿe¿@pp.Çk,TeFÿegrg¶ÅeF×@tT×@eF×@tT°ÿÍg¨‡¨‡¨‡¨‡°ÿÍg¨‡°õÛ»d¿@p¿@pFseFŸ¨‡F]¯°õ»d@ep@eFÇ@eFÿŸ@eFÇK	(ÿŸ‡°Fk×(T×¶×]„¿@p×(T×¶×¨‡@t	ÇK	íT	íÿ¶ÿ¶×¨‡@teF»d	eFÿe¿@pp.Çk,TeFÿeT×(T×¶×]›¿@e&¨‡¤eFs]¯°(T×¶×¨‡@t	ÇK	ÿakÿ¶LktÿŸ‡°Fkÿ¶LkteF¶Ÿ¯¶Fÿ»d]k˜Ÿê›¿@pFÇÿ^¶×(TVI×½¶ž@t	eFÿep@eFÇ@eFÿeFÿeFkeF×@eFÿeF¶W¿@p×(T×¶×@c	sk@tT×@eFÿeFÿeFÿeF×@tT×@eFÿeFÿep@eFÿØktÿ¬í˜.R°Í»teFÿtF»d	éI¶T×S¶Fs]¯°×]¯„@eeFÿ¬»d	seFŸ¨‡FT¨‡M¨‡¶xs
4íkÿ¶LkteF¶Ÿg˜kŸeF¯»d]C‡íÿØV°‡°FÿØktÿ¬gk·Ûkÿ¶Lktep³¶Fÿ»d]k˜Ÿê›¿@pFÇkIe»d]]Ç:FÿÍFÿ»dIkkeFÿeeFÿ¬»d	seFŸ¨‡FT×4Í×@tT×R˜ÿ¶×(T×¶×]¯ü4.°×gepÒÛ@eFÿâ×Q»	gkø¿@e»¿@p×(T×¶×@tTQgkSrk˜½K	íTg]]Q»	gk@eFÿŸ@eFÇK	ÿ¶×(T×¶×]¯@tT×4
eFÿeFÿeFÿeF×@tT×@eFÿeFÿeFÿeF×@tT×Q»	gkø¿@eTep4íkûûâep°(	¨‡°ÿŸ@eFÿeeÍ°Fÿ»dIéÍT×]¯eep	¶IpÛpT¨‡¶xkt	eFÿep@eFÇ@k@eFÿ@eFÿeFÿeT×(T×(T×¶×SeF»d	]¯ÿŸ@tT×(T×¶×	¶Fÿ»
-xFk‡T×¶p.ÇK	íT	íÿ¶k¿@eF¶»d]ep@eFÇ@eFÇ˜ÿ¶×(T×¶×]¶Fÿ»d]k˜Ÿê›¿@p¨‡¶ŸíT	íeFÿ¶ÿØ»T×	×(T×¶×@e¸í™ÙW¶×4
Ç¶×@e¨×(Tk‡F×@tT×Økÿ¶Lktep³K¶gkSrk˜ÿØk‡Fp.»dT¨I‡T×¶×(³.Ç@eFÿŸ‡FsÞeFs4íTeFÿe˜½¿@eeFÿ¬»d	seFŸ¨‡FT¨‡M¨‡¶xkt	eFÿep@N)¶eFÿÍFÇøFsK-»¿@p×(T×¶×@tTQ©¨‡¶T]»	¶Fÿc	4& d¶¿F»d	×»T×í]¯íÍ]×	¶×(xµ	eFÿep@eFC¼°(	¨‡ÿFsk@×@tT×°Fÿ¶ÿ¶×(T×¶×]¶ÿK	eFÿ»d@×k°FÿeeFÿ¬»d	seFŸ¨‡Fp›¿@eFŸ¨‡Fp›°×@eFÿeFk»d@ep@pFÿ¬gkSrkÿ¶ÿ¶F»d¿@eF¨‡FTeFÿ¯I»T»d¿@pF»d]øepFÿ¬FÿŸ@tT×¨‡»d@e¨‡T×e»d]]÷ÿ[¿@eFC¼°(	¨‡ÿÇkt	Ç@eFÿe¿@pFÿ¬K¶gkSrT&	eFÿep@eFk¶×(	¨seFŸ¨‡Fÿ¶ÿm@tFkeFjtT×4
eFÿeFÿeeFÿ»	¶Fÿe×	¶¿F»d	×»T×(×(T×¶×Srkÿ¶ÿ¶F»d¿@tF»d	¨‡°ÿÍg¨‡°Lø»d¶(T×Øs	k¶Fÿ¬‡Fÿ»d@ep@pFÿ¬gkSrFs˜.»dIék‡FP¸Wt¶×ÿ]í˜ÿ¬¯1³¶Í°»d¿@eF¨‡¨‡¨‡¨‡°Fÿ¬F×@tT×°×]¶FÍ¯¶ÿØk‡F×ÆCeFÿeeFÿ»	(ÿŸ@eFÇK°Í»	¶Fÿ¶ÿ¶g¨‡°ÿÍg¨‡°ÿÍg?@tT×°Fÿ¶ÿ¶×(T×¶×]¶ÿK	eFÿ»de»d]]¯ÍxÿØk‡F×ÆCeFÿeeFÿ¬»d@tF»d	¨‡°ÿÍg¨‡í/ÿ¶¶×	×@tT×@eFsk@×@tT×¨‡»d	í×	¶›¿@eTs
¼×¨»¬e:FÿÍFÿ»dIkkeFÿeeFÿ¬»d	seFŸ¨‡FT×4Í×@tT×R˜ÿ¶×(T×¶×]¯ü4
Ír³(T×¶×@e¸íSrFÿâj¿@p»¿@p×(T×¶×@tTQ©¨